services:
  neo4j:
    image: neo4j:community-ubi9
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/neo4j_custom_password
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
